CREATE FUNCTION public.generate_new_customer_access_code(p_customer_id uuid, p_admin_user_id uuid, p_notes text DEFAULT NULL::text) RETURNS json
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public', 'extensions'
    AS $$
DECLARE
    v_new_access_code text;
    v_hashed_new_code text;
    v_customer_name text;
    v_whatsapp_number text;
    v_old_hashed_code text;
    v_admin_name text;
    v_current_time timestamp with time zone := now();
    result json;
BEGIN
    SELECT username INTO v_admin_name
    FROM public.users WHERE id = p_admin_user_id AND status = 'active';
    
    IF v_admin_name IS NULL THEN
        RETURN json_build_object('success', false, 'error', 'Invalid admin user');
    END IF;
    
    SELECT c.access_code, c.whatsapp_number, c.name
    INTO v_old_hashed_code, v_whatsapp_number, v_customer_name
    FROM public.customers c WHERE c.id = p_customer_id;
    
    IF v_customer_name IS NULL THEN
        RETURN json_build_object('success', false, 'error', 'Customer not found');
    END IF;
    
    v_new_access_code := generate_unique_customer_access_code();
    v_hashed_new_code := encode(digest(v_new_access_code::bytea, 'sha256'), 'hex');
    
    IF v_new_access_code IS NULL THEN
        RETURN json_build_object('success', false, 'error', 'Failed to generate unique access code');
    END IF;
    
    UPDATE public.customers
    SET access_code = v_hashed_new_code,
        access_code_generated_at = v_current_time,
        updated_at = v_current_time
    WHERE id = p_customer_id;

    INSERT INTO public.customer_access_code_history (
        customer_id, old_access_code, new_access_code,
        generated_by, reason, notes
    ) VALUES (
        p_customer_id, v_old_hashed_code, v_hashed_new_code,
        p_admin_user_id, 'admin_regeneration', COALESCE(p_notes, 'Regenerated by admin')
    );
    
    INSERT INTO public.notifications (title, message, type, priority, metadata, deleted_at)
    VALUES (
        'Customer Access Code Regenerated',
        'Access code regenerated for customer: ' || v_customer_name || ' by admin: ' || v_admin_name,
        'customer_access_code_change', 'medium',
        json_build_object('customer_id', p_customer_id, 'customer_name', v_customer_name,
            'generated_by', v_admin_name, 'generated_at', v_current_time, 'notes', p_notes),
        NULL
    );
    
    INSERT INTO public.notifications (title, message, type, priority, metadata, deleted_at)
    VALUES (
        'New Access Code Generated',
        'Your access code has been updated by an administrator.',
        'customer_notification', 'high',
        json_build_object('customer_id', p_customer_id, 'generated_by', v_admin_name,
            'generated_at', v_current_time, 'notes', p_notes),
        NULL
    );
    
    INSERT INTO public.user_activity_logs (user_id, activity_type, description, metadata, created_at)
    VALUES (
        p_admin_user_id, 'customer_access_code_regenerated',
        'Generated new access code for customer: ' || v_customer_name,
        json_build_object('customer_id', p_customer_id, 'customer_name', v_customer_name, 'notes', p_notes),
        v_current_time
    );
    
    result := json_build_object(
        'success', true,
        'message', 'New access code generated successfully',
        'customer_id', p_customer_id,
        'customer_name', v_customer_name,
        'whatsapp_number', v_whatsapp_number,
        'new_access_code', v_new_access_code,
        'generated_by', v_admin_name,
        'generated_at', v_current_time
    );
    
    RETURN result;
    
EXCEPTION
    WHEN OTHERS THEN
        RETURN json_build_object('success', false, 'error', 'Failed to generate new access code: ' || SQLERRM);
END;
$$;


--
-- Name: generate_order_number(); Type: FUNCTION; Schema: public; Owner: -
--

