// This mapping allows us to match sidebar button names with database button codes
// It handles cases where the sidebar display name differs from the database code

export const buttonNameToCodeMap: Record<string, string> = {
  "Customer Master": "CUSTOMER_MASTER",
  "Ad Manager": "AD_MANAGER",
  "Products Manager": "PRODUCTS_MANAGER",
  "Delivery Settings": "DELIVERY_SETTINGS",
  "Orders Manager": "ORDERS_MANAGER",
  "Offer Management": "OFFER_MANAGEMENT",
  "Receiving": "RECEIVING",
  "Upload Vendor": "UPLOAD_VENDOR",
  "Create Vendor": "CREATE_VENDOR",
  "Manage Vendor": "MANAGE_VENDOR",
  "Start Receiving": "START_RECEIVING",
  "Receiving Records": "RECEIVING_RECORDS",
  "Vendor Records": "VENDOR_RECORDS",
  "Flyer Master": "FLYER_MASTER",
  "Product Master": "PRODUCT_MASTER",
  "Variation Manager": "VARIATION_MANAGER",
  "Offer Manager": "OFFER_MANAGER",
  "Flyer Templates": "FLYER_TEMPLATES",
  "Settings": "SETTINGS",
  "Offer Product Editor": "OFFER_PRODUCT_EDITOR",
  "Create New Offer": "CREATE_NEW_OFFER",
  "Pricing Manager": "PRICING_MANAGER",
  "ERP Entry Manager": "ERP_ENTRY_MANAGER",
  "Generate Flyers": "GENERATE_FLYERS",
  "Shelf Paper Manager": "SHELF_PAPER_MANAGER",
  "Coupon Dashboard": "COUPON_DASHBOARD",
  "Manage Campaigns": "MANAGE_CAMPAIGNS",
  "Customer Importer": "IMPORT_CUSTOMERS",
  "Coupon Reports": "COUPON_REPORTS",
  "Expense Manager": "EXPENSE_MANAGER",
  "Day Budget Planner": "DAY_BUDGET_PLANNER",
  "Monthly Manager": "MONTHLY_MANAGER",
  "Paid Manager": "PAID_MANAGER",
  "Expense Tracker": "EXPENSE_TRACKER",
  "Sales Report": "SALES_REPORT",
  "Monthly Breakdown": "MONTHLY_BREAKDOWN",
  "Over dues": "OVER_DUES",
  "Vendor Payments": "VENDOR_PAYMENTS",
  "Manual Scheduling": "MANUAL_SCHEDULING",
  "Upload Employees": "UPLOAD_EMPLOYEES",
  "Create Department": "CREATE_DEPARTMENT",
  "Create Level": "CREATE_LEVEL",
  "Create Position": "CREATE_POSITION",
  "Reporting Map": "REPORTING_MAP",
  "Assign Positions": "ASSIGN_POSITIONS",
  "Employee Files": "EMPLOYEE_FILES",
  "Fingerprint Transactions": "FINGERPRINT_TRANSACTIONS",
  "Salary and Wage": "SALARY_AND_WAGE",
  "Contact Management": "CONTACT_MANAGEMENT",
  "Document Management": "DOCUMENT_MANAGEMENT",
  "Salary & Wage Management": "SALARY_WAGE_MANAGEMENT",
  "Task Master": "TASK_MASTER",
  "Create Task Template": "CREATE_TASK_TEMPLATE",
  "View My Tasks": "VIEW_MY_TASKS",
  "Assign Tasks": "ASSIGN_TASKS",
  "Task Status": "TASK_STATUS",
  "Biometric Data": "BIOMETRIC_DATA",
  "Export Biometric Data": "EXPORT_BIOMETRIC_DATA",
  "View My Assignments": "VIEW_MY_ASSIGNMENTS",
  "Create User": "CREATE_USER",
  "User Permissions": "USER_PERMISSIONS",
  "Users": "USERS",
  "Create User Roles": "CREATE_USER_ROLES",
  "Assign Roles": "ASSIGN_ROLES",
  "ERP Connections": "ERP_CONNECTIONS",
  "Interface Access": "INTERFACE_ACCESS",
  "Button Access Control": "BUTTON_ACCESS_CONTROL",
  "Clear Tables": "CLEAR_TABLES",
  "Com Center": "COMMUNICATION_CENTER",
  "Reports & Stats": "REPORTS_STATS",
  "Branch Master": "BRANCH_MASTER",
  "Branch Performance": "BRANCH_PERFORMANCE",
  "View Task Templates": "VIEW_TASK_TEMPLATES",
  "Manage Products": "MANAGE_PRODUCTS",
  "Manage Admin Users": "MANAGE_ADMIN_USERS",
  "Manage Master Admin": "MANAGE_MASTER_ADMIN",
  "Sound Settings": "SOUND_SETTINGS",
  "Flyer Settings": "FLYER_SETTINGS",
  "Approval Permissions": "APPROVAL_PERMISSIONS",
  "Denomination": "DENOMINATION",
  "Petty Cash": "PETTY_CASH",
  "Approval Center": "APPROVAL_CENTER",
  "One Day Offer Manager": "ONE_DAY_OFFER_MANAGER"
};
